// Generated by CoffeeScript 1.9.3
(function() {
  var Article, ConfigArticleCode, Configure, ProcessCategory;

  ConfigArticleCode = (function() {
    function ConfigArticleCode() {}

    ConfigArticleCode.ARTICLE_UNKNOWN = 0;

    ConfigArticleCode.ARTICLE_CONTRACT_EMPL_TERM = 101;

    ConfigArticleCode.ARTICLE_POSITION_EMPL_TERM = 110;

    ConfigArticleCode.ARTICLE_INCOME_GROSS = 501;

    ConfigArticleCode.ARTICLE_INCOME_NETTO = 502;

    ConfigArticleCode.ARTICLE_CONTRACT_STAT_TERM = 102;

    ConfigArticleCode.ARTICLE_CONTRACT_WORK_TERM = 103;

    ConfigArticleCode.ARTICLE_CONTRACT_TASK_TERM = 104;

    ConfigArticleCode.ARTICLE_SCHEDULE_WORK = 201;

    ConfigArticleCode.ARTICLE_SALARY_BASE = 202;

    ConfigArticleCode.ARTICLE_TIMESHEET_SCHEDULE = 251;

    ConfigArticleCode.ARTICLE_TIMESHEET_WORKING = 252;

    ConfigArticleCode.ARTICLE_TIMESHEET_ABSENCE = 253;

    ConfigArticleCode.ARTICLE_TIMEHOURS_WORKING = 254;

    ConfigArticleCode.ARTICLE_TIMEHOURS_ABSENCE = 255;

    ConfigArticleCode.ARTICLE_HEALTH_INCOME_SUBJECT = 301;

    ConfigArticleCode.ARTICLE_SOCIAL_INCOME_SUBJECT = 302;

    ConfigArticleCode.ARTICLE_GARANT_INCOME_SUBJECT = 303;

    ConfigArticleCode.ARTICLE_HEALTH_INCOME_PARTICIP = 305;

    ConfigArticleCode.ARTICLE_SOCIAL_INCOME_PARTICIP = 306;

    ConfigArticleCode.ARTICLE_GARANT_INCOME_PARTICIP = 307;

    ConfigArticleCode.ARTICLE_HEALTH_BASIS_GENERAL = 311;

    ConfigArticleCode.ARTICLE_HEALTH_BASIS_MANDATORY = 312;

    ConfigArticleCode.ARTICLE_HEALTH_BASIS_LEGALCAP = 313;

    ConfigArticleCode.ARTICLE_SOCIAL_BASIS_GENERAL = 321;

    ConfigArticleCode.ARTICLE_SOCIAL_BASIS_PENSION = 322;

    ConfigArticleCode.ARTICLE_SOCIAL_BASIS_LEGALCAP = 323;

    ConfigArticleCode.ARTICLE_GARANT_BASIS_PENSION = 331;

    ConfigArticleCode.ARTICLE_GARANT_BASIS_LEGALCAP = 332;

    ConfigArticleCode.ARTICLE_HEALTH_EMPLOYEE_GENERAL = 341;

    ConfigArticleCode.ARTICLE_HEALTH_EMPLOYEE_MANDATORY = 342;

    ConfigArticleCode.ARTICLE_SOCIAL_EMPLOYEE_GENERAL = 351;

    ConfigArticleCode.ARTICLE_SOCIAL_EMPLOYEE_PENSION = 352;

    ConfigArticleCode.ARTICLE_GARANT_EMPLOYEE_PENSION = 361;

    ConfigArticleCode.ARTICLE_HEALTH_EMPLOYER_GEENRAL = 371;

    ConfigArticleCode.ARTICLE_HEALTH_EMPLOYER_MANDATORY = 372;

    ConfigArticleCode.ARTICLE_SOCIAL_EMPLOYER_GENERAL = 373;

    ConfigArticleCode.ARTICLE_TAXING_INCOME_SUBJECT = 401;

    ConfigArticleCode.ARTICLE_TAXING_INCOME_HEALTH = 402;

    ConfigArticleCode.ARTICLE_TAXING_INCOME_SOCIAL = 403;

    ConfigArticleCode.ARTICLE_TAXING_ADVANCES_INCOME = 411;

    ConfigArticleCode.ARTICLE_TAXING_ADVANCES_HEALTH = 412;

    ConfigArticleCode.ARTICLE_TAXING_ADVANCES_SOCIAL = 413;

    ConfigArticleCode.ARTICLE_TAXING_ADVANCES_BASIS_GENERAL = 414;

    ConfigArticleCode.ARTICLE_TAXING_ADVANCES_BASIS_SOLIDARY = 415;

    ConfigArticleCode.ARTICLE_TAXING_ADVANCES_GENERAL = 416;

    ConfigArticleCode.ARTICLE_TAXING_ADVANCES_SOLIDARY = 417;

    ConfigArticleCode.ARTICLE_TAXING_ADVANCES_TOTAL = 418;

    ConfigArticleCode.ARTICLE_TAXING_ALLOWANCE_PAYER = 421;

    ConfigArticleCode.ARTICLE_TAXING_ALLOWANCE_CHILD = 422;

    ConfigArticleCode.ARTICLE_TAXING_ALLOWANCE_DISABILITY = 423;

    ConfigArticleCode.ARTICLE_TAXING_ALLOWANCE_STUDYING = 424;

    ConfigArticleCode.ARTICLE_TAXING_REBATE_PAYER = 431;

    ConfigArticleCode.ARTICLE_TAXING_REBATE_CHILD = 432;

    ConfigArticleCode.ARTICLE_TAXING_BONUS_CHILD = 433;

    ConfigArticleCode.ARTICLE_TAXING_WITHHOLD_INCOME = 451;

    ConfigArticleCode.ARTICLE_TAXING_WITHHOLD_HEALTH = 452;

    ConfigArticleCode.ARTICLE_TAXING_WITHHOLD_SOCIAL = 453;

    ConfigArticleCode.ARTICLE_TAXING_WITHHOLD_BASIS_GENERAL = 454;

    ConfigArticleCode.ARTICLE_TAXING_WITHHOLD_GENERAL = 456;

    return ConfigArticleCode;

  })();

  ProcessCategory = (function() {
    function ProcessCategory() {}

    ProcessCategory.CATEGORY_TERMS = 0;

    ProcessCategory.CATEGORY_START = 1;

    ProcessCategory.CATEGORY_TIMES = 2;

    ProcessCategory.CATEGORY_AMOUNT = 3;

    ProcessCategory.CATEGORY_GROSS = 4;

    ProcessCategory.CATEGORY_NETTO = 5;

    ProcessCategory.CATEGORY_FINAL = 9;

    return ProcessCategory;

  })();

  Article = (function() {
    function Article(code, catg, pendings) {
      this.code = code;
      this.aatg = catg;
      this.pendings = pendings;
    }

    Article.prototype.Code = function() {
      return this.code;
    };

    Article.prototype.Catg = function() {
      return this.catg;
    };

    Article.prototype.Pendings = function() {
      return this.pendings;
    };

    Article.prototype.compareTo = function(other) {
      var compareResult;
      compareResult = this.Code() === other.Code() ? 0 : this.Code() - other.Code();
      return compareResult;
    };

    return Article;

  })();

  Configure = (function() {
    function Configure() {}

    Configure.EMPTY_PENDING_NAMES = {};

    Configure.PendingArticleNames1 = function(code1) {
      return [code1];
    };

    Configure.PendingArticleNames2(code1, code2)(function() {
      return [code1, code2];
    });

    Configure.PendingArticleNames3(code1, code2, code3)(function() {
      return [code1, code2, code3];
    });

    Configure.PendingArticleNames4(code1, code2, code3, code4)(function() {
      return [code1, code2, code3, code4];
    });

    Configure.PendingArticleNames5(code1, code2, code3, code4, code5)(function() {
      return [code1, code2, code3, code4, code5];
    });

    Configure.PendingArticleNames9(code1, code2, code3, code4, code5, code6, code7, code8, code9)(function() {
      return [code1, code2, code3, code4, code5, code6, code7, code8, code9];
    });

    Configure.ConfigureContractTermArticles = function() {
      var articleArray, configCategory;
      configCategory = ProcessCategory.prototype.CATEGORY_TERMS;
      articleArray = [new Article(ConfigArticleCode.prototype.ARTICLE_CONTRACT_EMPL_TERM, configCategory, this.EMPTY_PENDING_NAMES), new Article(ConfigArticleCode.prototype.ARTICLE_POSITION_EMPL_TERM, configCategory, this.PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_CONTRACT_EMPL_TERM))];
      return articleArray;
    };

    Configure.ConfigurePositionTimeArticles = function() {
      var articleArray, configCategory;
      configCategory = ProcessCategory.prototype.CATEGORY_TIMES;
      articleArray = [new Article(ConfigArticleCode.prototype.ARTICLE_SCHEDULE_WORK, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_POSITION_EMPL_TERM)), new Article(ConfigArticleCode.prototype.ARTICLE_TIMESHEET_SCHEDULE, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_SCHEDULE_WORK)), new Article(ConfigArticleCode.prototype.ARTICLE_TIMESHEET_WORKING, configCategory, PendingArticleNames2(ConfigArticleCode.prototype.ARTICLE_TIMESHEET_SCHEDULE, ConfigArticleCode.prototype.ARTICLE_POSITION_EMPL_TERM)), new Article(ConfigArticleCode.prototype.ARTICLE_TIMESHEET_ABSENCE, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_TIMESHEET_WORKING)), new Article(ConfigArticleCode.prototype.ARTICLE_TIMEHOURS_WORKING, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_TIMESHEET_WORKING)), new Article(ConfigArticleCode.prototype.ARTICLE_TIMEHOURS_ABSENCE, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_TIMESHEET_ABSENCE))];
      return articleArray;
    };

    Configure.ConfigureGrossIncomeArticles = function() {
      var articleArray, configCategory;
      configCategory = ProcessCategory.prototype.CATEGORY_AMOUNT;
      articleArray = [new Article(ConfigArticleCode.prototype.ARTICLE_SALARY_BASE, configCategory, PendingArticleNames2(ConfigArticleCode.prototype.ARTICLE_TIMEHOURS_WORKING, ConfigArticleCode.prototype.ARTICLE_TIMEHOURS_ABSENCE))];
      return articleArray;
    };

    Configure.ConfigureTotalIncomeArticles = function() {
      var articleArray, configCategory;
      configCategory = ProcessCategory.prototype.CATEGORY_FINAL;
      articleArray = [new Article(ConfigArticleCode.prototype.ARTICLE_INCOME_GROSS, configCategory, EMPTY_PENDING_NAMES), new Article(ConfigArticleCode.prototype.ARTICLE_INCOME_NETTO, configCategory, PendingArticleNames9(ConfigArticleCode.prototype.ARTICLE_INCOME_GROSS, ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_TOTAL, ConfigArticleCode.prototype.ARTICLE_TAXING_BONUS_CHILD, ConfigArticleCode.prototype.ARTICLE_TAXING_WITHHOLD_GENERAL, ConfigArticleCode.prototype.ARTICLE_HEALTH_EMPLOYEE_GENERAL, ConfigArticleCode.prototype.ARTICLE_HEALTH_EMPLOYEE_MANDATORY, ConfigArticleCode.prototype.ARTICLE_SOCIAL_EMPLOYEE_GENERAL, ConfigArticleCode.prototype.ARTICLE_SOCIAL_EMPLOYEE_PENSION, ConfigArticleCode.prototype.ARTICLE_GARANT_EMPLOYEE_PENSION))];
      return articleArray;
    };

    Configure.ConfigureNettoDeductsArticles = function() {
      var articleArray, configCategory;
      configCategory = ProcessCategory.prototype.CATEGORY_NETTO;
      articleArray = [new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_TOTAL, configCategory, PendingArticleNames2(ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_GENERAL, ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_SOLIDARY)), new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_GENERAL, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_BASIS_GENERAL)), new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_SOLIDARY, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_BASIS_SOLIDARY)), new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_WITHHOLD_GENERAL, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_TAXING_WITHHOLD_BASIS_GENERAL)), new Article(ConfigArticleCode.prototype.ARTICLE_HEALTH_EMPLOYEE_GENERAL, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_HEALTH_BASIS_GENERAL)), new Article(ConfigArticleCode.prototype.ARTICLE_HEALTH_EMPLOYEE_MANDATORY, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_HEALTH_BASIS_MANDATORY)), new Article(ConfigArticleCode.prototype.ARTICLE_SOCIAL_EMPLOYEE_GENERAL, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_SOCIAL_BASIS_GENERAL)), new Article(ConfigArticleCode.prototype.ARTICLE_SOCIAL_EMPLOYEE_PENSION, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_SOCIAL_BASIS_PENSION)), new Article(ConfigArticleCode.prototype.ARTICLE_GARANT_EMPLOYEE_PENSION, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_GARANT_BASIS_PENSION))];
      return articleArray;
    };

    Configure.ConfigureBasisHealthArticles = function() {
      var articleArray, configCategory;
      configCategory = ProcessCategory.prototype.CATEGORY_NETTO;
      articleArray = [new Article(ConfigArticleCode.prototype.ARTICLE_HEALTH_INCOME_SUBJECT, configCategory, EMPTY_PENDING_NAMES), new Article(ConfigArticleCode.prototype.ARTICLE_HEALTH_INCOME_PARTICIP, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_HEALTH_INCOME_SUBJECT)), new Article(ConfigArticleCode.prototype.ARTICLE_HEALTH_BASIS_GENERAL, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_HEALTH_INCOME_PARTICIP)), new Article(ConfigArticleCode.prototype.ARTICLE_HEALTH_BASIS_MANDATORY, configCategory, PendingArticleNames2(ConfigArticleCode.prototype.ARTICLE_HEALTH_BASIS_GENERAL, ConfigArticleCode.prototype.ARTICLE_HEALTH_INCOME_PARTICIP)), new Article(ConfigArticleCode.prototype.ARTICLE_HEALTH_BASIS_LEGALCAP, configCategory, PendingArticleNames2(ConfigArticleCode.prototype.ARTICLE_HEALTH_BASIS_GENERAL, ConfigArticleCode.prototype.ARTICLE_HEALTH_INCOME_PARTICIP))];
      return articleArray;
    };

    Configure.ConfigureBasisSocialArticles = function() {
      var articleArray, configCategory;
      configCategory = ProcessCategory.prototype.CATEGORY_NETTO;
      articleArray = [new Article(ConfigArticleCode.prototype.ARTICLE_SOCIAL_INCOME_SUBJECT, configCategory, EMPTY_PENDING_NAMES), new Article(ConfigArticleCode.prototype.ARTICLE_SOCIAL_INCOME_PARTICIP, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_SOCIAL_INCOME_SUBJECT)), new Article(ConfigArticleCode.prototype.ARTICLE_SOCIAL_BASIS_GENERAL, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_SOCIAL_INCOME_PARTICIP)), new Article(ConfigArticleCode.prototype.ARTICLE_SOCIAL_BASIS_PENSION, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_SOCIAL_INCOME_PARTICIP)), new Article(ConfigArticleCode.prototype.ARTICLE_SOCIAL_BASIS_LEGALCAP, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_SOCIAL_INCOME_PARTICIP))];
      return articleArray;
    };

    Configure.ConfigureBasisGarantArticles = function() {
      var articleArray, configCategory;
      configCategory = ProcessCategory.prototype.CATEGORY_NETTO;
      articleArray = [new Article(ConfigArticleCode.prototype.ARTICLE_GARANT_INCOME_SUBJECT, configCategory, EMPTY_PENDING_NAMES), new Article(ConfigArticleCode.prototype.ARTICLE_GARANT_INCOME_PARTICIP, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_GARANT_INCOME_SUBJECT)), new Article(ConfigArticleCode.prototype.ARTICLE_GARANT_BASIS_PENSION, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_GARANT_INCOME_PARTICIP)), new Article(ConfigArticleCode.prototype.ARTICLE_GARANT_BASIS_LEGALCAP, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_GARANT_INCOME_PARTICIP))];
      return articleArray;
    };

    Configure.ConfigureBasisTaxingArticles = function() {
      var articleArray, configCategory;
      configCategory = ProcessCategory.prototype.CATEGORY_NETTO;
      articleArray = [new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_INCOME_SUBJECT, configCategory, EMPTY_PENDING_NAMES), new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_INCOME_HEALTH, configCategory, EMPTY_PENDING_NAMES), new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_INCOME_SOCIAL, configCategory, EMPTY_PENDING_NAMES)];
      return articleArray;
    };

    Configure.ConfigureBasisAdvancesArticles = function() {
      var articleArray, configCategory;
      configCategory = ProcessCategory.prototype.CATEGORY_NETTO;
      articleArray = [new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_INCOME, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_TAXING_INCOME_SUBJECT)), new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_HEALTH, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_TAXING_INCOME_HEALTH)), new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_SOCIAL, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_TAXING_INCOME_SOCIAL)), new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_BASIS_GENERAL, configCategory, PendingArticleNames3(ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_INCOME, ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_HEALTH, ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_SOCIAL)), new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_BASIS_SOLIDARY, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_BASIS_GENERAL))];
      return articleArray;
    };

    Configure.ConfigureBasisWithholdArticles = function() {
      var articleArray, configCategory;
      configCategory = ProcessCategory.prototype.CATEGORY_NETTO;
      articleArray = [new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_WITHHOLD_INCOME, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_TAXING_INCOME_SUBJECT)), new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_WITHHOLD_HEALTH, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_TAXING_INCOME_HEALTH)), new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_WITHHOLD_SOCIAL, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_TAXING_INCOME_SOCIAL)), new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_WITHHOLD_BASIS_GENERAL, configCategory, PendingArticleNames3(ConfigArticleCode.prototype.ARTICLE_TAXING_WITHHOLD_INCOME, ConfigArticleCode.prototype.ARTICLE_TAXING_WITHHOLD_HEALTH, ConfigArticleCode.prototype.ARTICLE_TAXING_WITHHOLD_SOCIAL))];
      return articleArray;
    };

    Configure.ConfigureAllowanceTaxisArticles = function() {
      var articleArray, configCategory;
      configCategory = ProcessCategory.prototype.CATEGORY_NETTO;
      articleArray = [new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_ALLOWANCE_PAYER, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_INCOME)), new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_ALLOWANCE_DISABILITY, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_INCOME)), new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_ALLOWANCE_STUDYING, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_INCOME)), new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_ALLOWANCE_CHILD, configCategory, PendingArticleNames1(ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_INCOME))];
      return articleArray;
    };

    Configure.ConfigureRebateTaxisArticles = function() {
      var articleArray, configCategory;
      configCategory = ProcessCategory.prototype.CATEGORY_NETTO;
      articleArray = [new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_REBATE_PAYER, configCategory, PendingArticleNames4(ConfigArticleCode.prototype.ARTICLE_TAXING_ALLOWANCE_PAYER, ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_TOTAL, ConfigArticleCode.prototype.ARTICLE_TAXING_ALLOWANCE_DISABILITY, ConfigArticleCode.prototype.ARTICLE_TAXING_ALLOWANCE_STUDYING)), new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_REBATE_CHILD, configCategory, PendingArticleNames3(ConfigArticleCode.prototype.ARTICLE_TAXING_ALLOWANCE_CHILD, ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_TOTAL, ConfigArticleCode.prototype.ARTICLE_TAXING_REBATE_PAYER)), new Article(ConfigArticleCode.prototype.ARTICLE_TAXING_BONUS_CHILD, configCategory, PendingArticleNames3(ConfigArticleCode.prototype.ARTICLE_TAXING_ADVANCES_TOTAL, ConfigArticleCode.prototype.ARTICLE_TAXING_REBATE_PAYER, ConfigArticleCode.prototype.ARTICLE_TAXING_REBATE_CHILD))];
      return articleArray;
    };

    Configure.ConfigureArticles = function() {
      return this.ConfigureContractTermArticles();
    };

    return Configure;

  })();

  module.exports = {
    ConfigArticleCode: ConfigArticleCode,
    ProcessCategory: ProcessCategory,
    Article: Article,
    Configure: Configure
  };

}).call(this);

//# sourceMappingURL=Playground.js.map
