// Generated by CoffeeScript 1.9.3
(function() {
  var playground, should;

  should = require('should');

  playground = require('../LibraryCode/Playground');

  describe('TestLibrary', function() {
    return it('Should_Return_53_For_Articles_Length', function() {
      var articlesAll;
      articlesAll = playground.Configure.ConfigureArticles();
      return 53..should.equal(articlesAll.length);
    });
  });

}).call(this);

//# sourceMappingURL=PlaygroundTest.js.map
